server:
  port: 8080

spring:
  application:
    name: RENIEC-IN-DEVELOPMENT
  datasource:
    url: jdbc:h2:mem:dev_reniec;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

mail:
  tm:
    email: 904additional@rustyload.com
    password: +aC,m2Zk9y
    domain: rustyload.com
